# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode

development:
  <<: *default
  database: ruby007project2_development
test:
  <<: *default
  database: ruby007project2_test

production:
  <<: *default
  database: ruby007project2_production
